# Generated by Django 3.1.3 on 2020-11-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_community', '0002_auto_20201120_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avg_star',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='avg_vote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.TextField(),
        ),
    ]
