# Generated by Django 3.1.3 on 2020-12-07 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_community', '0003_auto_20201205_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_comment',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie_community.movie'),
            preserve_default=False,
        ),
    ]
