# Generated by Django 3.1.3 on 2020-11-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='today_chocie',
            new_name='today_choice',
        ),
    ]
